name: hub-adapter-node
base: core20
version: '0.1'
summary: Adapter in NODE
description: |
  Adapter in NODE

grade: stable
confinement: strict

apps:
  hub-adapter-node:
    command: bin/node $SNAP/index.js

parts:
  node:
    plugin: dump
    source: https://nodejs.org/dist/latest-v12.x/node-v12.20.2-linux-x64.tar.xz
    stage:
      - bin
      - include
      - lib
  adapter:
    plugin: nil
    after: [node]
    source: .
    override-build: |
      npm install
      cp -a node_modules $SNAPCRAFT_PART_INSTALL/
      cp index.js $SNAPCRAFT_PART_INSTALL/

plugs:
  sockdir:
    interface: content
    content: sockdir
    target: $SNAP_COMMON/sockdir
    default-provider: thinghub:sockdir
